### ISSUE TITLE
Rename Module (slightly) to avoid errors in newer ProcessWire versions.

### ISSUE THREAD

**Issue by netcarver** [juergenweb/JKPublishingOptions#1]
Not sure when this started happening, but just had this issue crop up trying to install JKPublishingOptions on 2 PW sites.

https://github.com/processwire/processwire-issues/issues/1658

With reference to the second image in that report, it looks like PW requires a slight renaming of this module for it to continue being compatible with ProcessWire.

**Comment by juergenweb** [comment]
Thanks for your report! You are right. I have changed the names a little bit - to clearify: I have changed the K from JK to lowercase (Jk). This is what PW is complaining about. I have done this on all files (CSS and JS files) even if it was not necessaray, but I do not want to mix it up.
On my local installation it works - so please try it and let me know, so I can close this issue.

Best regards Jürgen

**Comment by netcarver** [comment]
Yes, that's exactly what I did with my local copy and the issue resolved on the sites I tried it on. Closing this issue now - but I will leave the issue open on the PW core as it needs to be able to handle this with any module if it happens again.

Thank you, Jürgen
